import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const REGION_DATA = [
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11140', sggName: '중구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11560', sggName: '영등포구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11530', sggName: '구로구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11500', sggName: '강서구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11350', sggName: '노원구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11320', sggName: '도봉구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11290', sggName: '성북구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11740', sggName: '강동구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11710', sggName: '송파구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11650', sggName: '서초구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11305', sggName: '강북구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11200', sggName: '성동구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11440', sggName: '마포구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11410', sggName: '서대문구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11620', sggName: '관악구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11230', sggName: '동대문구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11260', sggName: '중랑구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11380', sggName: '은평구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11545', sggName: '금천구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11590', sggName: '동작구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11680', sggName: '강남구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11110', sggName: '종로구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11170', sggName: '용산구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11215', sggName: '광진구' },
  { sidoCode: '11', sidoName: '서울특별시', sggCode: '11470', sggName: '양천구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26170', sggName: '동구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26710', sggName: '기장군' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26110', sggName: '중구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26260', sggName: '동래구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26500', sggName: '수영구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26350', sggName: '해운대구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26140', sggName: '서구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26320', sggName: '북구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26230', sggName: '부산진구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26470', sggName: '연제구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26200', sggName: '영도구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26290', sggName: '남구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26440', sggName: '강서구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26380', sggName: '사하구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26530', sggName: '사상구' },
  { sidoCode: '26', sidoName: '부산광역시', sggCode: '26410', sggName: '금정구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27110', sggName: '중구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27230', sggName: '북구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27140', sggName: '동구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27710', sggName: '달성군' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27170', sggName: '서구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27290', sggName: '달서구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27200', sggName: '남구' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27720', sggName: '군위군' },
  { sidoCode: '27', sidoName: '대구광역시', sggCode: '27260', sggName: '수성구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28177', sggName: '미추홀구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28185', sggName: '연수구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28260', sggName: '서구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28110', sggName: '중구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28200', sggName: '남동구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28237', sggName: '부평구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28710', sggName: '강화군' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28140', sggName: '동구' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28720', sggName: '옹진군' },
  { sidoCode: '28', sidoName: '인천광역시', sggCode: '28245', sggName: '계양구' },
  { sidoCode: '29', sidoName: '광주광역시', sggCode: '29155', sggName: '남구' },
  { sidoCode: '29', sidoName: '광주광역시', sggCode: '29110', sggName: '동구' },
  { sidoCode: '29', sidoName: '광주광역시', sggCode: '29170', sggName: '북구' },
  { sidoCode: '29', sidoName: '광주광역시', sggCode: '29140', sggName: '서구' },
  { sidoCode: '29', sidoName: '광주광역시', sggCode: '29200', sggName: '광산구' },
  { sidoCode: '30', sidoName: '대전광역시', sggCode: '30140', sggName: '중구' },
  { sidoCode: '30', sidoName: '대전광역시', sggCode: '30200', sggName: '유성구' },
  { sidoCode: '30', sidoName: '대전광역시', sggCode: '30170', sggName: '서구' },
  { sidoCode: '30', sidoName: '대전광역시', sggCode: '30110', sggName: '동구' },
  { sidoCode: '30', sidoName: '대전광역시', sggCode: '30230', sggName: '대덕구' },
  { sidoCode: '31', sidoName: '울산광역시', sggCode: '31140', sggName: '남구' },
  { sidoCode: '31', sidoName: '울산광역시', sggCode: '31200', sggName: '북구' },
  { sidoCode: '31', sidoName: '울산광역시', sggCode: '31710', sggName: '울주군' },
  { sidoCode: '31', sidoName: '울산광역시', sggCode: '31170', sggName: '동구' },
  { sidoCode: '31', sidoName: '울산광역시', sggCode: '31110', sggName: '중구' },
  { sidoCode: '36', sidoName: '세종특별자치시', sggCode: '36110', sggName: '세종특별자치시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41110', sggName: '수원시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41196', sggName: '부천시 오정구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41194', sggName: '부천시 소사구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41192', sggName: '부천시 원미구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41461', sggName: '용인시 처인구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41390', sggName: '시흥시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41370', sggName: '오산시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41360', sggName: '남양주시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41150', sggName: '의정부시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41133', sggName: '성남시 중원구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41111', sggName: '수원시 장안구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41480', sggName: '파주시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41115', sggName: '수원시 팔달구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41130', sggName: '성남시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41450', sggName: '하남시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41131', sggName: '성남시 수정구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41170', sggName: '안양시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41830', sggName: '양평군' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41250', sggName: '동두천시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41800', sggName: '연천군' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41630', sggName: '양주시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41273', sggName: '안산시 단원구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41210', sggName: '광명시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41117', sggName: '수원시 영통구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41550', sggName: '안성시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41820', sggName: '가평군' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41670', sggName: '여주시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41650', sggName: '포천시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41610', sggName: '광주시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41570', sggName: '김포시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41290', sggName: '과천시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41463', sggName: '용인시 기흥구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41430', sggName: '의왕시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41310', sggName: '구리시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41287', sggName: '고양시 일산서구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41281', sggName: '고양시 덕양구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41271', sggName: '안산시 상록구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41220', sggName: '평택시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41173', sggName: '안양시 동안구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41135', sggName: '성남시 분당구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41113', sggName: '수원시 권선구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41465', sggName: '용인시 수지구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41500', sggName: '이천시' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41171', sggName: '안양시 만안구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41285', sggName: '고양시 일산동구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41591', sggName: '화성시 만세구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41593', sggName: '화성시 효행구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41595', sggName: '화성시 병점구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41597', sggName: '화성시 동탄구' },
  { sidoCode: '41', sidoName: '경기도', sggCode: '41410', sggName: '군포시' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43770', sggName: '음성군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43800', sggName: '단양군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43111', sggName: '청주시 상당구' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43130', sggName: '충주시' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43720', sggName: '보은군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43740', sggName: '영동군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43745', sggName: '증평군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43760', sggName: '괴산군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43730', sggName: '옥천군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43112', sggName: '청주시 서원구' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43150', sggName: '제천시' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43114', sggName: '청주시 청원구' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43750', sggName: '진천군' },
  { sidoCode: '43', sidoName: '충청북도', sggCode: '43113', sggName: '청주시 흥덕구' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44250', sggName: '계룡시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44150', sggName: '공주시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44825', sggName: '태안군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44210', sggName: '서산시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44710', sggName: '금산군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44133', sggName: '천안시 서북구' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44760', sggName: '부여군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44200', sggName: '아산시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44790', sggName: '청양군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44810', sggName: '예산군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44270', sggName: '당진시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44800', sggName: '홍성군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44180', sggName: '보령시' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44770', sggName: '서천군' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44131', sggName: '천안시 동남구' },
  { sidoCode: '44', sidoName: '충청남도', sggCode: '44230', sggName: '논산시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46720', sggName: '곡성군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46710', sggName: '담양군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46870', sggName: '영광군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46770', sggName: '고흥군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46800', sggName: '장흥군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46890', sggName: '완도군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46900', sggName: '진도군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46820', sggName: '해남군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46230', sggName: '광양시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46830', sggName: '영암군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46810', sggName: '강진군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46860', sggName: '함평군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46880', sggName: '장성군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46110', sggName: '목포시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46150', sggName: '순천시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46730', sggName: '구례군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46790', sggName: '화순군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46780', sggName: '보성군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46170', sggName: '나주시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46130', sggName: '여수시' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46840', sggName: '무안군' },
  { sidoCode: '46', sidoName: '전라남도', sggCode: '46910', sggName: '신안군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47130', sggName: '경주시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47170', sggName: '안동시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47280', sggName: '문경시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47110', sggName: '포항시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47190', sggName: '구미시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47830', sggName: '고령군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47850', sggName: '칠곡군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47920', sggName: '봉화군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47840', sggName: '성주군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47900', sggName: '예천군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47930', sggName: '울진군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47940', sggName: '울릉군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47770', sggName: '영덕군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47760', sggName: '영양군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47111', sggName: '포항시 남구' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47210', sggName: '영주시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47290', sggName: '경산시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47820', sggName: '청도군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47113', sggName: '포항시 북구' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47150', sggName: '김천시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47230', sggName: '영천시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47250', sggName: '상주시' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47730', sggName: '의성군' },
  { sidoCode: '47', sidoName: '경상북도', sggCode: '47750', sggName: '청송군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48820', sggName: '고성군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48240', sggName: '사천시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48720', sggName: '의령군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48860', sggName: '산청군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48121', sggName: '창원시 의창구' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48270', sggName: '밀양시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48880', sggName: '거창군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48123', sggName: '창원시 성산구' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48127', sggName: '창원시 마산회원구' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48220', sggName: '통영시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48250', sggName: '김해시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48310', sggName: '거제시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48330', sggName: '양산시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48730', sggName: '함안군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48740', sggName: '창녕군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48850', sggName: '하동군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48870', sggName: '함양군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48890', sggName: '합천군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48129', sggName: '창원시 진해구' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48125', sggName: '창원시 마산합포구' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48840', sggName: '남해군' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48170', sggName: '진주시' },
  { sidoCode: '48', sidoName: '경상남도', sggCode: '48120', sggName: '창원시' },
  { sidoCode: '50', sidoName: '제주특별자치도', sggCode: '50130', sggName: '서귀포시' },
  { sidoCode: '50', sidoName: '제주특별자치도', sggCode: '50110', sggName: '제주시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51110', sggName: '춘천시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51820', sggName: '고성군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51800', sggName: '양구군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51780', sggName: '철원군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51760', sggName: '평창군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51720', sggName: '홍천군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51230', sggName: '삼척시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51190', sggName: '태백시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51170', sggName: '동해시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51130', sggName: '원주시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51790', sggName: '화천군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51730', sggName: '횡성군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51210', sggName: '속초시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51150', sggName: '강릉시' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51770', sggName: '정선군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51810', sggName: '인제군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51830', sggName: '양양군' },
  { sidoCode: '51', sidoName: '강원특별자치도', sggCode: '51750', sggName: '영월군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52800', sggName: '부안군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52770', sggName: '순창군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52140', sggName: '익산시' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52740', sggName: '장수군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52720', sggName: '진안군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52190', sggName: '남원시' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52790', sggName: '고창군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52180', sggName: '정읍시' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52750', sggName: '임실군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52111', sggName: '전주시 완산구' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52113', sggName: '전주시 덕진구' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52130', sggName: '군산시' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52210', sggName: '김제시' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52710', sggName: '완주군' },
  { sidoCode: '52', sidoName: '전북특별자치도', sggCode: '52730', sggName: '무주군' },
];

async function main() {
  console.log('Seeding region codes...');
  await prisma.regionCode.deleteMany();
  await prisma.regionCode.createMany({ data: REGION_DATA });
  console.log(`Seeded ${REGION_DATA.length} region codes.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

